{% set name = "pyhrf" %}
{% set version = "0.5.0.post1" %}
{% set sha256 = "dc2384973631ba5df01d136c0f2643f67f1df7501580c9cd1bb50b66fcafee24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k or not np==111]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - numpy >=1.6,<1.12
    - scipy >=0.9
    - nibabel >=1.1,<2.1.0
    - sympy >=0.7
    - nipy >=0.3.0
    - matplotlib >=1.1
    - colorama
    - click
    - sphinx
    - sphinx_bootstrap_theme
  run:
    - python
    - numpy x.x
    - numpy >=1.6,<1.12
    - scipy >=0.9
    - nibabel >=1.1,<2.1.0
    - sympy >=0.7
    - nipy >=0.3.0
    - matplotlib >=1.1
    - colorama
    - click
    - sphinx
    - sphinx_bootstrap_theme

test:
  imports:
    - pyhrf
    - pyhrf.test

about:
  home: http://github.com/pyhrf/pyhrf
  license: CeCILL v2
  license_file: LICENSE
  summary: 'pyhrf is a set of tools to analyze fMRI data and specifically study hemodynamics'

  description: |
    PyHRF is a Python library for the analysis of fMRI data based on the study of hemodynamics.
  doc_url: http://www.pyhrf.org
  dev_url: https://github.com/pyhrf/pyhrf

extra:
  recipe-maintainers:
    - himito
    - ainafp
