travis:
  secure:
    BINSTAR_TOKEN: WA+p0CqVLVcgezVJhMSCXvPmz1KFBZLfOhQ6NSI3d38cv9yQrkHPOH13leH/h62X0BKAJuUTyRRf9UbL2SVHLX3oz45+NQXO3HhZfvu+kylyHtdRzxQb/eN0EjvEFF5waOkc/CnGr/E8mxC6V9LmT9pkIdLjHrIXFiZ/abYNG7MBC3yW8OvV4rJESO0lJ61dTjHEvZlXwTWI7MWewReji8A18Pnou9GiN1YR9rFez2mbhWNesTrWXYLZgTSNRl3jtFNsi/XxBb9INr/Z9FZ38oL0xSUy7vJXO8t+wkm7waDtch7YWS/9ss+NNZwFMm+BwW6QOJnd0ImdKOH4g4DClQBXP4oe5Yv5aj4aRCKpSl+JJxrEx4V0AcnvxnDmzTfFvuxGQnIFsbmpz5526NC+5KkHAbGo4/vQIkUKpFoCAjaJqQeQ0PBeklaaO4WSXajBYx+AQR5S+17s8gWmV/bYai9t+BfSaGogSmR/UM8RjUk6h4rcLv7TY14K+tgs0EzXPxgVOADihoSiRw2/EA3N63aQMVM31SOnSDrk8nfdGr3fKVhGsM0pmHr/jMswhRlWMcdM0wjQ3jkJAHpHX6uj8xGS0584kmyOcCKFa4W+mwXhBbCrNbz2ljAOS+lpd5uFFvk1PLVe/6f9zju3T8bRpcBpiDCzS5pF+yv/ixRnsi8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
