appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NBO6ZX8N3T5cfaxYzvsmKjlInNPp4tEAoqdkGdalPQd8thh6tCxE2VnvPoqkUEcVjBmS3p/tk9z1T2BmM95b9V87Z2jZTMc2nDoZ30V2DL3axliyn5CFBwHKKmhu5RftiFAPVnjjfj9Pzv4qIE3D6qGL7lsEHYE5SNuoXlS+JMU9OTYApEb6BF5fNCpdZSrc254XLS/cbc5gPeAPaaif4dI39v2FXWbppk7hUIT9Bk0bOzfaZZFnuj7ILMNN7wAoBUT4CRMGG4pge/Q2cZbwpe3+FbTKgdF2RI2iB5muMva7JsrvGBDs2hTNkH4BaWurVtOdfk8Q/P+uJS0lMblpBpx+fS14gYeLO3fAWMGhtZ38f2i0ebClscjpcvlkym4Z+EPXwFgrQad0zU0E2yg1cAYFrlrrYwcSGJ2YIy8J9xQ0xerPXYpk5Hkhhp0yNieqGwewLmSG6I0NiJM2z27eA951UYoAM2nUDiPzKnwixwBAxEvUI4hhjiuLCUtd4wJqP/abdx3I5h/4kFOm0XJmKdnEa9q15y6fOu01dZ2oA7Ea77kg5ygfbEkXxbfe7FvDHWrbb41FDxmE1tgl8J4IIEuve4qCa02ophMZolSmyPKeTnGO7NawEGKWqM3MEnTrkIn7nfA7IL+TQEa9mrwoQZrcBs3VQ/OgAUzzvPlZkEk=}
